### ISSUE TITLE
Implicitly add 'util' to dependencies because it is used in the codebase

### ISSUE THREAD

**Issue by azhiv** [sinonjs/sinon#2488]
**Describe the bug**
`util` npm package is referenced from the [code](https://github.com/sinonjs/sinon/blob/ef76b5bb169f61a28a7830bf3955feb3939e8174/lib/sinon/assert.js#L8) but is not claimed to be a dependency as per `package.json`. This leads to inconsistent behaviour when other modules in the consumer application also depend on `util`. Sinon is not tied to a specific version of the module, which may resolve to other versions depending on the adjacent modules.

Why is this even a problem? Starting from v0.12.1 `util` contains a top level condition which accesses `process.env.NODE_DEBUG` which is not compatible with running in a browser. Depending on the bundler `process` may be polyfilled, but this is not done by default in Webpack starting from v5.

A possible solution would be to add `util` dependency to `package.json` to capture a specific version of the library (v0.12.0 doesn't produce the issue with `process`).

**To Reproduce**

1. Clone repo git@github.com:azhiv/ember-sinon-msw.git
2. Run `yarn` + `yarn test:ember -s`
3. Tests are not run, the web page is empty. Check the console in the browser for the error.

**Expected behavior**
Tests are run successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/32125472/213257393-8c884fb2-0072-441a-93ff-07d602c64495.png)

**Context (please complete the following information):**

- Library version: 15.0.1
- Environment: Chrome 108.0.5359.124
- Example URL: http://localhost:7357
- Other libraries you are using: [msw](https://github.com/mswjs/msw)

**Comment by fatso83** [comment]
Good point. Relying on Node built-ins being shimmed successfully by bundlers when building for browsers does not seem like a bullet-proof solution, as it. But it looks like depending on the [NPM package`util` by browserify](https://www.npmjs.com/package/util) is the right solution here. @mroderick or @mantoni? 

Related to #2448.

**Comment by mantoni** [comment]
We have `util` added as a dependency in `referee` and `referee-sinon` already. So it's currently implicitly installed through the `@sinonjs/referee-sinon` dependency here.

:+1: for adding it as a dependency explicitly here too.

**Comment by fatso83** [comment]
From the webpack build log above it at least _seems_ like implicitly depending on the `util` shim does not "work". Unfortunately, after testing it out (adding `util` and doing `yarn link` to sinon locally and using `yarn link sinon` in your repo) neither does _explicitly_ depending on it. And according to the `util` docs, neither should it: 

[From the `util` package's own description](https://www.npmjs.com/package/util):
> You usually do not have to install util yourself. If your code runs in Node.js, util is built in. If your code runs in the browser, bundlers like [browserify](https://github.com/browserify/browserify) or [webpack](https://github.com/webpack/webpack) (up to version 4 -- [see this documentation](https://webpack.js.org/configuration/resolve/#resolvefallback) for how to include polyfills like util in webpack 5+) also include the util module.

Note the version 5 caveat, [as I can see you are using version 5 of webpack](https://github.com/azhiv/ember-sinon-msw/blob/main/package.json#L94). Just _having_ the dependency is not enough, you also need to _configure_ the fallback yourself. I took a pass at figuring out how Ember does this, as I could not see any webpack config in your project, but I only stumbled upon some vegetables (Broccoli), so that is up to you to figure out :)

The docs show how it would normally look (observe the `process` field):
![image](https://user-images.githubusercontent.com/618076/213496294-964c6d35-a55c-46c4-83a9-3eb0beaba028.png)

So closing this as it seems to be down to user configurable bits. Shout out if I got it wrong!

**Comment by andreyfel** [comment]
Having a custom config in the app is fine, what we were trying to say is that sinon needs to specify the exact version of util it depends on. It would justify the need for that special configuration.
In the current situation, some random version of util is picked up. In our case, we have a yarn workspace. Adding a new dep (msw.js) to one of the apps in the workspace made it necessary to add a custom config to the other apps because before adding that new dep util was resolved to an older version (0.10), after that it picked up a new version (0.12.1) across the yarn workspace which requires a custom webpack configuration.

**Comment by fatso83** [comment]
What version of `util` we depend upon is a bit hard to tell, in a way, as most of the time it is whatever is built-in to Node, but I am sure we can stick the external package used by bundlers to some version, no problem. Still won't make the issue above go away. If you could try adding the relevant config to your project I could use that as a verification step that it works fine. 

I can also just do `npm i util@latest` ASAP and publish a new version without testing: whatever floats your boat.

**Comment by andreyfel** [comment]
We use `ember-auto-import` which is using webpack@5 under the hood to import sinon. We've added the following settings to make it work:
```
  autoImport: {
      webpack: {
        plugins: [
          new webpack.DefinePlugin({
            'process.env.NODE_DEBUG': 'false',
          }),
        ],
      }
  }
```

**Comment by azhiv** [comment]
I updated the initial repo with a fix, the tests are not failing now.
